[theme]

# Primary accent for interactive elements
primaryColor = '#9DC08B'

# Background color for the main content area
backgroundColor = '#4D4D4D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#4E6E81'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
